### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by pfoxeh** [joezeng/cambridge#1]
Partway through a game of the Pacer mode, I received this error:

Error

scene/game.lua:31: bad argument #1 to 'draw' (Drawable expected, got nil)

Traceback

[C]: in function 'draw'
scene/game.lua:31: in function 'render'
main.lua:76: in function 'draw'
[C]: in function 'xpcall'

Unsure if this was due to a third strike being issued and the game not knowing how to respond, or which level I had reached being a problem, or something else. Please advise of any further information needed to seed out what occurred.

**Comment by joezeng** [comment]
Thanks for the alert, I'll try my best to figure out what happened. (I've sometimes had trouble with that mode myself.)

**Comment by smiegrin** [comment]
I Hypothesize, upon investigation, that this occurs at the transition to level 21. In `load/graphics.lua`, there are a total of 20 indexed backgrounds and one named background for the title screen.

At level 21, however, the game tries to select background number 20 which doesn't exist. This makes a nil value and crashes the draw function.

The question is this, then: do we want to change how the game mode requests backgrounds for its levels (such as loop back around to the first background using a simple modulo operation), or do we want to add more backgrounds for the game?

**Comment by joezeng** [comment]
Yeah, it looks like the other person who reported it also mentioned the bug happening about 20 minutes in, after segment 220 or so.

Looks like I didn't anticipate people playing that far in, lol (or that I forgot it has more than 20 sections).

**Comment by smiegrin** [comment]
Indeed. Following the rules, I hardly get to level 2 or 3 after the 15th lap or so. X]

It helps that the game logic is letting me gather up to 200 strikes, though... useful for testing!

So what's the way forward, though? More Backgrounds?

**Comment by joezeng** [comment]
I think until we get more backgrounds (maybe of a futuristic theme since backgrounds 11 and up represent scenes from the 11th century etc.) we should cap it at 20 for the time being.

**Comment by joezeng** [comment]
Fixed for the time being by 704e6dae555b0871d4dcf9f4afca292bf5dc7344.
