### ISSUE TITLE
Alter Window Size

### ISSUE THREAD

**Issue by smiegrin** [joezeng/cambridge#2]
Hello! Wonderful project you have here.

I have discovered that my laptop, which has a high-DPI screen, renders the game very small. I modified the 'conf.lua' file to change the window size (since the window is not resizable), but found that the screen was rendered at the same size in just the corner of the larger window.

I would like to propose that some configuration be available to change the size of the window.

Would it be best to make the window resizable, to allow a fullscreen mode, to have an options menu for different resolutions/aspect ratios, or perhaps a mixture of all?

**Comment by joezeng** [comment]
Merging into #5.
